### ISSUE TITLE
Problem with deepUpdate of generic objects with version 1.2.0

### ISSUE THREAD

**Issue by unekinn** [AlexGalays/immupdate#13]
Came across this problem while updating to the latest version of space-lift today. Great work on that, by the way!

### Minimal example

```typescript
import { deepUpdate } from "immupdate"

function handleChange<T extends object>(values: T, value: T[keyof T], name: keyof T) {
    return deepUpdate(values)
        .at(name)
        .set(value);
};
```
Test it yourself by downloading [this example gist](https://gist.github.com/larskinn/7e139500243eeab21b44aa0c54552cc3) and running `npm install && npm run build`

### Expected result

It compiles, like it did with version 1.1.7

### Actual result

```
example.ts:4:12 - error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '((index: number) => BoundUpdater<T, [T] extends [any[]]
? T[number & keyof T] | undefined : never>) | (<K extends keyof T>(key: K) => BoundUpdater<T, T[K]>)' has no compatible call signatures.

4     return deepUpdate(values)
             ~~~~~~~~~~~~~~~~~~
5         .at(name)
  ~~~~~~~~~~~~~~~~~
```

### Other info

Tested with TypeScript versions 2.8.4, 2.9.2 and 3.0.1, with the same results.

**Comment by AlexGalays** [comment]
I don't like the look of that!

**Comment by unekinn** [comment]
By the way, here's a more representative example, just to demonstrate the usefulness without adding any other dependencies. This also works in 1.1.7 and is broken in 1.2.0.

```typescript
import { deepUpdate } from "immupdate";

class Form<T extends object> {
    constructor(values: T) {
        this.values = values;
    }

    values: T;

    handleChange<TVal extends keyof T>(field: TVal, value: T[TVal]): void {
        const newValues = deepUpdate(this.values)
            .at(field)
            .set(value);

        this.values = newValues;
    }
}

interface Person {
    name: string;
    age: number;
    coolness: "rad" | "weak";
}

const personForm = new Form<Person>({
    name: "Jake",
    age: 29,
    coolness: "rad"
});

personForm.handleChange("age", 65); // should work
personForm.handleChange("coolness", "weak"); // should work
personForm.handleChange("age", "65"); // should not compile
personForm.handleChange("coolness", "lame"); // should not compile
```


The actual usage is in a generic React form component, where the form values are stored in React's state and `handleChange` is passed to child components for handling form field change events.

I tried fiddling with the definition of the `AtUpdater` and `BoundAtUpdater` mapped types to see if I could make it work, but no luck so far.

**Comment by AlexGalays** [comment]
Thanks, I will have a look;

Funny, I have the same kind of component in our latest app :)

**Comment by AlexGalays** [comment]
No luck. This really smells like a limitation of TS.

Btw, if you only need one level of keys, you could just use update:

`const newValues = update<any, any>(this.values, { [field]: value })`

It suffers form the same problem, unfortunately (even though it only uses the default Pick). Though the compromise of any is not so bad here as it's encapsulated in a well typed function.

**Comment by unekinn** [comment]
I think your `update` suggestion would  be a good enough solution for now, thanks!

The irritating thing though is that it works the `deepUpdate(target)` function is specialized as `ObjectBoundAtUpdater<TARGET, TARGET>`, so it seems to be a limitation of the conditional types.

I removed the ~`BoundUpdater`~ (EDIT: `AtUpdater`) and `BoundAtUpdater` types, and added some overrides to `deepUpdate`, like this:

```typescript
export function deepUpdate<TARGET extends any[]>(target: TARGET): ArrayBoundAtUpdater<TARGET, TARGET>
export function deepUpdate<TARGET extends object>(target: TARGET): ObjectBoundAtUpdater<TARGET, TARGET>
export function deepUpdate<TARGET extends any[]>(): ArrayAtUpdater<TARGET, TARGET>
export function deepUpdate<TARGET extends object>(): ObjectAtUpdater<TARGET, TARGET>
export function deepUpdate(target?: any): any {
  return new _Updater({ type: 'root', boundTarget: target })
}
```

This seems to work, and doesn't break any existing tests. I can submit a PR with the change and a test case if this seems okay with you.

**Comment by AlexGalays** [comment]
Interesting, this kind of validates the story of conditional types not being smart enough. I will test this a bit locally.

**Comment by AlexGalays** [comment]
Hello @larskinn 

You said you removed `BoundUpdater ` and `BoundAtUpdater `; does that mean you also added overloaded functions for all the subsequent levels (`at()`, etc) ?

**Comment by unekinn** [comment]
Sorry, I mistyped earlier. I removed `AtUpdater` and `BoundAtUpdater`.

Here's the diff:

```diff
diff --git a/immupdate.ts b/immupdate.ts
index 5d873f3..aa1a074 100644
--- a/immupdate.ts
+++ b/immupdate.ts
@@ -35,12 +35,6 @@ export const DELETE = {} as any as undefined
 
 export type Leaf = string | number | boolean | null | symbol |┬áDate |┬áFunction
 
-export type AtUpdater<TARGET, CURRENT> =
-  [CURRENT] extends [any[]] ? ArrayAtUpdater<TARGET, CURRENT> : ObjectAtUpdater<TARGET, CURRENT>
-
-export type BoundAtUpdater<TARGET, CURRENT> =
-  [CURRENT] extends [any[]] ? ArrayBoundAtUpdater<TARGET, CURRENT> : ObjectBoundAtUpdater<TARGET, CURRENT>
-
 export type Updater<TARGET, CURRENT> =
   [CURRENT] extends [any[]] ? ArrayUpdater<TARGET, CURRENT> :
   [CURRENT] extends [Leaf] ? AnySetter<TARGET, CURRENT> : ObjectUpdater<TARGET, CURRENT>
@@ -336,8 +330,10 @@ function clone(obj: any): any {
   return cloned
 }
 
-export function deepUpdate<TARGET extends object>(target: TARGET): BoundAtUpdater<TARGET, TARGET>
-export function deepUpdate<TARGET extends object>(): AtUpdater<TARGET, TARGET>
+export function deepUpdate<TARGET extends any[]>(target: TARGET): ArrayBoundAtUpdater<TARGET, TARGET>
+export function deepUpdate<TARGET extends object>(target: TARGET): ObjectBoundAtUpdater<TARGET, TARGET>
+export function deepUpdate<TARGET extends any[]>(): ArrayAtUpdater<TARGET, TARGET>
+export function deepUpdate<TARGET extends object>(): ObjectAtUpdater<TARGET, TARGET>
 export function deepUpdate(target?: any): any {
   return new _Updater({ type: 'root', boundTarget: target })
-}
\ No newline at end of file
+}
```

And a test case:
```diff
diff --git a/test/test.ts b/test/test.ts
index 95779ea..3a82b25 100644
--- a/test/test.ts
+++ b/test/test.ts
@@ -728,6 +728,40 @@ describe('immupdate', () => {
       })
     })
 
+    it('works with generic objects', () => {
+      function f1<T extends object, TVal extends keyof T>(values: T, name: TVal, value: T[TVal]) {
+        return deepUpdate(values)
+            .at(name)
+            .set(value)
+      };
+      function f2<T extends object, TVal extends keyof T>(values: T, name: TVal, value: T[TVal]) {
+        return deepUpdate<T>()
+            .at(name)
+            .set(value)(values)
+      };
+
+      interface Dude {
+        name: string
+        age: number
+        coolness: "rad" | "weak"
+      }
+
+      const dude: Dude = {
+        name: "Jake",
+        age: 29,
+        coolness: "rad" 
+      }
+
+      const update1 = f1(dude, "age", 12)
+      const update2 = f2(update1, "coolness", "weak")
+
+      expect(update2).toEqual({
+        name: "Jake",
+        age: 12,
+        coolness: "weak"
+      })
+    })
+
   })
 
 })
\ No newline at end of file
```

**Comment by AlexGalays** [comment]
Played with it some more... I just don't have a solution at the moment.

Your fix above only works for the first level, if we apply the same fix for any arbitrary levels we end up with more or less the same code we had before the fixes for 2.8. I reverted to that and made them compile, it seems TS 3.0.0 helps a lot but there are two main issues:

- This usage now compiles again:

```
deepUpdate<{ kiki: { koko: number } }>()
  .at('kiki')
  .at('koko')
  .at('toExponential')
```

- The error messages are TERRIBLE.

So it seems the remedy is worse than the disease :(

**Comment by unekinn** [comment]
Aha, I see. Thanks for trying, anyway  :)

Maybe it's better to at least have `deepUpdate` work on the first level of a generic object, instead of none, if that doesn't break anything else / make errors worse? Or did thas couse some issues as well?

It's your time, so you decide. I can definitely live with your `update<any, any>` workaround, and I would think this isn't the most common of use cases, so you shouldn't need to waste any more energy on it. Let's hope TypeScript gets powerful enough to handle this in the future.

**Comment by larskinn** [comment]
Or maybe it's better to at least have `deepUpdate` work on the first level of a generic object, instead of none, if that doesn't break anything else / make errors worse? Or did thas couse some issues as well?

**Comment by AlexGalays** [comment]
I just released 1.2.1 which does just that: Fix the first level of deepUpdate when working with generics.

Thank you for your perseverance :)
